//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HouseHoldGood
    {
        public int HouseHoldGoodId { get; set; }
        public int HouseholdId { get; set; }
        public int Good { get; set; }
        public int Quantity { get; set; }
        public int QuantityUOM { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_Good T_Good { get; set; }
        public virtual T_HouseHold T_HouseHold { get; set; }
        public virtual T_UOM T_UOM { get; set; }
    }
}
