//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HouseholdCulture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_HouseholdCulture()
        {
            this.T_HouseHoldCultureLastMonths = new HashSet<T_HouseHoldCultureLastMonths>();
            this.T_HouseholdCultureLastSeason = new HashSet<T_HouseholdCultureLastSeason>();
            this.T_HouseHoldCultureTool = new HashSet<T_HouseHoldCultureTool>();
        }
    
        public int HouseholdCultureId { get; set; }
        public int HouseholdId { get; set; }
        public int AssetTypeId { get; set; }
        public decimal Area { get; set; }
        public int AreaUOM { get; set; }
        public int CultureDiversityId { get; set; }
        public int PaidWorkersQty { get; set; }
        public bool IsPurchased { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_AssetType T_AssetType { get; set; }
        public virtual T_CultureDiversity T_CultureDiversity { get; set; }
        public virtual T_HouseHold T_HouseHold { get; set; }
        public virtual T_UOM T_UOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldCultureLastMonths> T_HouseHoldCultureLastMonths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseholdCultureLastSeason> T_HouseholdCultureLastSeason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldCultureTool> T_HouseHoldCultureTool { get; set; }
    }
}
