//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAPEconomicActivity
    {
        public int PAPEconomicActivityId { get; set; }
        public int PAPId { get; set; }
        public int EconomicActivityId { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_EconomicActivity T_EconomicActivity { get; set; }
        public virtual T_PAP T_PAP { get; set; }
    }
}
