//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAPResidence
    {
        public int PAPResidenceId { get; set; }
        public int PAPId { get; set; }
        public int ResidenceId { get; set; }
        public bool IsPermanent { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual T_PAP T_PAP { get; set; }
        public virtual T_Residence T_Residence { get; set; }
    }
}
