//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Property()
        {
            this.T_PropertyAttachment = new HashSet<T_PropertyAttachment>();
        }
    
        public int PropertyId { get; set; }
        public int Owner { get; set; }
        public int User { get; set; }
        public int LandId { get; set; }
        public int VillageId { get; set; }
        public int LACId { get; set; }
        public int Investigator { get; set; }
        public int InvestigatorPoint { get; set; }
        public Nullable<int> TopographerPoint { get; set; }
        public string PictureName { get; set; }
        public string Picture { get; set; }
        public int PropertyType { get; set; }
        public decimal Surface { get; set; }
        public Nullable<int> SurfaceUOM { get; set; }
        public Nullable<System.DateTime> CultureStartDate { get; set; }
        public Nullable<int> CultureOccupationType { get; set; }
        public Nullable<int> TreeMaturity { get; set; }
        public Nullable<int> TreeQty { get; set; }
        public Nullable<int> RoomQty { get; set; }
        public Nullable<decimal> StructureLength { get; set; }
        public Nullable<decimal> StructureWidth { get; set; }
        public Nullable<int> RoofType { get; set; }
        public Nullable<int> WallType { get; set; }
        public Nullable<int> SoilType { get; set; }
        public Nullable<int> StructureUOM { get; set; }
        public Nullable<System.DateTime> MeasurementSignatureDate { get; set; }
        public Nullable<int> TopographerId { get; set; }
        public Nullable<System.DateTime> MeasurementDate { get; set; }
        public string GPSDevice { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public string Comments { get; set; }
        public bool IsHabitable { get; set; }
        public bool HasOwner { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_AssetType T_AssetType { get; set; }
        public virtual T_Employee T_Employee { get; set; }
        public virtual T_Employee T_Employee1 { get; set; }
        public virtual T_LAC T_LAC { get; set; }
        public virtual T_Land T_Land { get; set; }
        public virtual T_List T_List { get; set; }
        public virtual T_List T_List1 { get; set; }
        public virtual T_List T_List2 { get; set; }
        public virtual T_List T_List3 { get; set; }
        public virtual T_List T_List4 { get; set; }
        public virtual T_PAP T_PAP { get; set; }
        public virtual T_PAP T_PAP1 { get; set; }
        public virtual T_Point T_Point { get; set; }
        public virtual T_Point T_Point1 { get; set; }
        public virtual T_UOM T_UOM { get; set; }
        public virtual T_UOM T_UOM1 { get; set; }
        public virtual T_Village T_Village { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PropertyAttachment> T_PropertyAttachment { get; set; }
    }
}
