//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Request()
        {
            this.T_Approval = new HashSet<T_Approval>();
            this.T_LACRequest = new HashSet<T_LACRequest>();
            this.T_RequestAttachment = new HashSet<T_RequestAttachment>();
        }
    
        public int RequestId { get; set; }
        public int RequestType { get; set; }
        public string RequestStatus { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public int Requestor { get; set; }
        public int CurrentStep { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Approval> T_Approval { get; set; }
        public virtual T_Employee T_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LACRequest> T_LACRequest { get; set; }
        public virtual T_List T_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RequestAttachment> T_RequestAttachment { get; set; }
    }
}
