//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAPSys.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HouseHold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_HouseHold()
        {
            this.T_HouseHoldAttachment = new HashSet<T_HouseHoldAttachment>();
            this.T_HouseHoldCompensation = new HashSet<T_HouseHoldCompensation>();
            this.T_HouseHoldCulture = new HashSet<T_HouseHoldCulture>();
            this.T_HouseHoldCultureTool = new HashSet<T_HouseHoldCultureTool>();
            this.T_HouseHoldGood = new HashSet<T_HouseHoldGood>();
            this.T_HouseHoldMembers = new HashSet<T_HouseHoldMembers>();
            this.T_HouseHoldProperty = new HashSet<T_HouseHoldProperty>();
            this.T_HouseHoldResidence = new HashSet<T_HouseHoldResidence>();
            this.T_HouseHoldRevenue = new HashSet<T_HouseHoldRevenue>();
            this.T_PAP = new HashSet<T_PAP>();
            this.T_HouseHoldSocioElements = new HashSet<T_HouseHoldSocioElements>();
        }
    
        public int HouseHoldId { get; set; }
        public int HouseHoldResponsible { get; set; }
        public int HouseHoldNumber { get; set; }
        public bool PreviouslyCompensated { get; set; }
        public string CompensationUse { get; set; }
        public int ResidenceId { get; set; }
        public Nullable<decimal> LastWeekExpense { get; set; }
        public bool FishOrMeat { get; set; }
        public bool EnoughFood { get; set; }
        public bool SkinDesease { get; set; }
        public int PaidWorkersQty { get; set; }
        public string PaidWorkersTimes { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_Person T_Person { get; set; }
        public virtual T_Residence T_Residence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldAttachment> T_HouseHoldAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldCompensation> T_HouseHoldCompensation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldCulture> T_HouseHoldCulture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldCultureTool> T_HouseHoldCultureTool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldGood> T_HouseHoldGood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldMembers> T_HouseHoldMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldProperty> T_HouseHoldProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldResidence> T_HouseHoldResidence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldRevenue> T_HouseHoldRevenue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PAP> T_PAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HouseHoldSocioElements> T_HouseHoldSocioElements { get; set; }
    }
}
