//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Approval
    {
        public int ApprovalId { get; set; }
        public int RequestId { get; set; }
        public int Approver { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string ApprovalStatus { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovalComments { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_Employee T_Employee { get; set; }
        public virtual T_Request T_Request { get; set; }
    }
}
