//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HouseHoldProperty
    {
        public int HouseHoldPropertyId { get; set; }
        public int HouseholdId { get; set; }
        public int LandId { get; set; }
        public int DistanceFromResidence { get; set; }
        public int DistanceUOM { get; set; }
        public int PropertyWorkerType { get; set; }
        public decimal CultivatedArea { get; set; }
        public int CultivatedAreaUOM { get; set; }
        public decimal FallowArea { get; set; }
        public int FallowAreaUOM { get; set; }
        public bool IsOwner { get; set; }
        public decimal Rent { get; set; }
        public int PropertySource { get; set; }
        public int AcquisitionYear { get; set; }
        public bool IsCultivatedLastYear { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_HouseHold T_HouseHold { get; set; }
        public virtual T_Land T_Land { get; set; }
        public virtual T_List T_List { get; set; }
        public virtual T_List T_List1 { get; set; }
        public virtual T_UOM T_UOM { get; set; }
        public virtual T_UOM T_UOM1 { get; set; }
        public virtual T_UOM T_UOM2 { get; set; }
    }
}
