//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAPLAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PAPLAC()
        {
            this.T_PAPLACAttachment = new HashSet<T_PAPLACAttachment>();
        }
    
        public int PAPLACId { get; set; }
        public int LACId { get; set; }
        public int PAPId { get; set; }
        public string Comments { get; set; }
        public int PaymentPreference { get; set; }
        public System.DateTime FormSubmissionDate { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual T_LAC T_LAC { get; set; }
        public virtual T_List T_List { get; set; }
        public virtual T_PAP T_PAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PAPLACAttachment> T_PAPLACAttachment { get; set; }
    }
}
